version: 1.0
app:
  instances:
    min: 1
    max: 2
  resources:
    cpu: 1
  env:
    - name: JVM_ARGS # q: make that as a top level 'jvmArguments' property?
      value: "-DenvironmentType=stage"
    - name: MY_ENV
      value: "1"
    - name: sslconn
      value: "false"
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  version: "3c6f5871-823b-47ab-ae24-cd2a601a6944"
  # Set the Java runtime version since sometimes (usually) the pom.xml compiler settings are 1.8
  java: 17
